import { test, expect } from '@playwright/test';

test('AdminEtablissement', async ({ page }) => {
  await page.goto('http://localhost:8080/');
  await page.getByPlaceholder('Enter Email Address').click();
  await page.getByPlaceholder('Enter Email Address').fill('abdotest2023@gmail.com');
  await page.getByPlaceholder('Enter Email Address').press('Tab');
  await page.getByPlaceholder('Enter Password').fill('test');
  await page.getByPlaceholder('Enter Password').press('Enter');
  await page.getByRole('listitem').click();
  await page.getByText('Admin', { exact: true }).click();
  await page.getByText('abdotest2023@gmail.com').click();
  await page.getByRole('img', { name: 'Neil image' }).click();
  await page.getByRole('heading', { name: 'Admin D\'etablissement' }).click();
  await page.getByText('Gestion des directeurs Gestion des profs Gestion des Interventions Profil Déconn').click();
  await page.getByRole('link', { name: 'Profil' }).click();
  await page.getByText('Email:PPR:Établissement:Nom:Prénom: Modifier').click();
  await page.getByRole('button', { name: 'Modifier' }).click();
  await page.locator('.mb-4 > .border').first().click();
  await page.locator('.mb-4 > .border').first().press('ArrowRight');
  await page.locator('.mb-4 > .border').first().press('ArrowRight');
  await page.locator('.mb-4 > .border').first().press('ArrowRight');
  await page.locator('.mb-4 > .border').first().press('ArrowRight');
  await page.locator('.mb-4 > .border').first().press('ArrowRight');
  await page.locator('.mb-4 > .border').first().press('ArrowRight');
  await page.locator('.mb-4 > .border').first().fill('Abderrahman');
  await page.getByRole('button', { name: 'Modifer' }).click();
  await page.getByRole('button', { name: 'Modifier' }).click();
  await page.locator('.mb-4 > .border').first().click();
  await page.locator('.mb-4 > .border').first().press('ArrowRight');
  await page.locator('.mb-4 > .border').first().press('ArrowRight');
  await page.locator('.mb-4 > .border').first().fill('Abderrahmane');
  await page.getByRole('button', { name: 'Modifer' }).click();
  await page.getByRole('link', { name: 'Gestion des Interventions' }).click();
  await page.getByLabel('PPR').click();
  await page.getByLabel('PPR').fill('6666666');
  await page.getByLabel('Intitulé intervention').click();
  await page.getByLabel('Intitulé intervention').press('CapsLock');
  await page.getByLabel('Intitulé intervention').fill('T');
  await page.getByLabel('Intitulé intervention').press('CapsLock');
  await page.getByLabel('Intitulé intervention').fill('Test intitulé d\'interventin');
  await page.getByLabel('Nombre Heure').click();
  await page.getByLabel('Nombre Heure').fill('42');
  await page.getByLabel('Année Scolaire').click();
  await page.getByLabel('Année Scolaire').fill('2022/2023');
  await page.locator('#underline_select').selectOption('Semestre 1');
  await page.getByLabel('Date Debut').fill('2023-06-02');
  await page.getByLabel('Date Fin').fill('2023-06-30');
  await page.getByRole('button', { name: 'Soumettre' }).click();
  await page.getByText('InfoInfo alert! Intervention Crée avec Succes.');
  await page.getByText('Info alert! Intervention Crée avec Succes.');
  await page.getByText('Ajouter une intervention').click();
  await page.getByRole('link', { name: 'Gestion des profs' }).click();
  await page.getByText('Listes des profsPPRNOMPRENOM DATE DE NAISSANCE ETABLISSEMNT GRADE TYPE Ajouter 1');
  await page.getByRole('heading', { name: 'Listes des profs' }).click();
  await page.getByRole('cell', { name: 'PPR', exact: true }).click();
  await page.getByRole('cell', { name: 'NOM', exact: true }).click();
  await page.getByRole('cell', { name: 'PRENOM' }).click();
  await page.getByRole('cell', { name: 'DATE DE NAISSANCE' }).click();
  await page.getByRole('cell', { name: 'ETABLISSEMNT' }).click();
  await page.getByRole('cell', { name: 'GRADE' }).click();
  await page.getByRole('cell', { name: 'TYPE' }).click();
  await page.getByRole('button', { name: 'Ajouter' }).click();
  await page.getByLabel('PPR:').click();
  await page.getByLabel('PPR:').fill('123456');
  await page.getByLabel('Nom:', { exact: true }).click();
  await page.getByLabel('Nom:', { exact: true }).fill('test');
  await page.getByLabel('Nom:', { exact: true }).press('Tab');
  await page.getByLabel('Prenom:').fill('test');
  await page.getByLabel('DATE_NAISSANCE:').fill('2023-06-02');
  await page.getByRole('combobox', { name: 'Grade:' }).selectOption('1');
  await page.getByLabel('Email:').click();
  await page.getByLabel('Email:').fill('testtest@testeur.fr');
  await page.getByRole('button', { name: 'Ajouter' }).nth(1).click();
  await page.waitForTimeout(15000);
  await page.getByRole('row', { name: '123456 test test 2023-06-02 Faculté des Lettres et des Sciences Humaines Professeur d Enseignemet Superieur prof Editer Supprimer' }).getByRole('link', { name: 'Editer' }).click();
  await page.getByLabel('Nom:', { exact: true }).click();
  await page.getByLabel('Nom:', { exact: true }).fill('testeur');
  await page.getByRole('button', { name: 'Soumettre' }).click();
  await page.waitForTimeout(15000);
  await page.getByRole('row', { name: '123456 testeur test 2023-06-02 Faculté des Lettres et des Sciences Humaines Professeur d Enseignemet Superieur prof Editer Supprimer' }).getByRole('button', { name: 'Supprimer' }).click();
  await page.getByRole('link', { name: 'Gestion des directeurs' }).click();
  await page.getByText('Listes des directeurs d\'établissementNOMPRENOMPPR EMAIL ETABLISSEMNT TYPE Ajoute').click();
  await page.getByRole('heading', { name: 'Listes des directeurs d\'établissement' }).click();
  await page.getByRole('cell', { name: 'NOM', exact: true }).click();
  await page.getByRole('cell', { name: 'PRENOM' }).click();
  await page.getByRole('cell', { name: 'PPR' }).click();
  await page.getByRole('cell', { name: 'EMAIL' }).click();
  await page.getByRole('cell', { name: 'ETABLISSEMNT' }).click();
  await page.getByRole('cell', { name: 'TYPE' }).click();
  await page.getByRole('button', { name: 'Ajouter' }).click();
  await page.getByLabel('Email:').click();
  await page.getByLabel('Email:').fill('testtest@tester.fr');
  await page.getByLabel('PPR:').click();
  await page.getByLabel('PPR:').fill('123654');
  await page.getByLabel('Nom:', { exact: true }).click();
  await page.getByLabel('Nom:', { exact: true }).fill('test');
  await page.getByLabel('Nom:', { exact: true }).press('Tab');
  await page.getByLabel('Prénom:').fill('test');
  await page.getByRole('button', { name: 'Ajouter' }).nth(1).click();
  await page.getByRole('heading', { name: 'Admin D\'etablissement' }).click();
  await page.getByText('Déconnexion').click();
});