import { test, expect } from '@playwright/test';

test('testBosss', async ({ page }) => {
  await page.goto('http://localhost:8080/');
  await page.getByPlaceholder('Entrer l\'e-mail').fill('boss@admin.com');
  await page.getByPlaceholder('Entrer l\'e-mail').press('Tab');
  await page.getByPlaceholder('Entrer le mot de passe').fill('test');
  await page.getByPlaceholder('Entrer le mot de passe').press('Enter');
  await page.getByText('Admin', { exact: true }).click();
  await page.getByText('boss@admin.com').click();
  await page.getByRole('img', { name: 'Neil image' }).click();
  await page.locator('.border').click();
  await page.getByRole('heading', { name: 'Listes des admins d\'etablissements' }).click();
  await page.getByRole('columnheader', { name: 'email' }).click();
  await page.getByRole('columnheader', { name: 'PPR' }).click();
  await page.getByRole('columnheader', { name: 'Nom', exact: true }).click();
  await page.getByRole('columnheader', { name: 'Prenom' }).click();
  await page.getByRole('columnheader', { name: 'Etablissement' }).click();
  await page.getByRole('button', { name: 'Ajouter' }).click();
  await page.getByLabel('PPR:').click();
  await page.getByLabel('PPR:').fill('321654');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('testadmin@etab.com');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('admin@etab.com');
  await page.getByLabel('Nom:', { exact: true }).click();
  await page.getByLabel('Nom:', { exact: true }).fill('test');
  await page.getByLabel('Nom:', { exact: true }).press('Tab');
  await page.getByLabel('Prénom:').fill('test');
  await page.getByRole('combobox', { name: 'Etablisssement:' }).selectOption('2');
  await page.getByRole('button', { name: 'Ajouter' }).nth(1).click();

  await page.getByLabel('PPR:').click();
  await page.getByLabel('PPR:').fill('987654');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('aadmin@etab.com');
  await page.getByLabel('Nom:', { exact: true }).click();
  await page.getByLabel('Nom:', { exact: true }).fill('test');
  await page.getByLabel('Nom:', { exact: true }).press('Tab');
  await page.getByLabel('Prénom:').fill('test');
  await page.getByLabel('Prénom:').press('Tab');
  await page.getByRole('button', { name: 'Ajouter' }).nth(1).click();
  await page.getByRole('link', { name: 'Profil' }).click();
  await page.getByRole('button', { name: 'Modifier' }).click();
  await page.locator('.mb-4 > .border').first().click();
  await page.locator('.mb-4 > .border').first().fill('boss');
  await page.getByRole('button', { name: 'Modifer' }).click();
  await page.getByRole('button', { name: 'Modifier' }).click();
  await page.locator('.mb-4 > .border').first().click();
  await page.locator('.mb-4 > .border').first().fill('boss1');
  await page.getByRole('button', { name: 'Modifer' }).click();
  await page.getByRole('link', { name: 'Gestion des etablissements' }).click();
  await page.getByRole('button', { name: 'Ajouter' }).click();
  await page.getByLabel('code:').click();
  await page.getByLabel('code:').fill('65432');
  await page.getByLabel('Nom:').click();
  await page.getByLabel('Nom:').press('CapsLock');
  await page.getByLabel('Nom:').fill('ENSA');
  await page.getByLabel('Nom:').press('CapsLock');
  await page.getByLabel('Telephone:').click();
  await page.getByLabel('Telephone:').fill('0655967517');
  await page.getByLabel('Fax:').click();
  await page.getByLabel('Fax:').fill('0655967517');
  await page.getByLabel('ville:').click();
  await page.getByLabel('ville:').fill('Tanger');
  await page.getByLabel('Nbr_enseignants:').click();
  await page.getByLabel('Nbr_enseignants:').fill('50');
  await page.getByRole('button', { name: 'Ajouter' }).nth(1).click();
  await page.getByRole('row', { name: '65432 ENSA 0655967517 0655967517 Tanger 50 Edit Delete' }).getByRole('link', { name: 'Edit' }).click();
  await page.getByLabel('Nom:').click();
  await page.getByLabel('Nom:').press('CapsLock');
  await page.getByLabel('Nom:').fill('ENSAT');
  await page.getByLabel('Nom:').press('CapsLock');
  await page.getByRole('button', { name: 'Soumettre' }).click();
  await page.getByRole('row', { name: '65432 ENSAT 0655967517 0655967517 Tanger 50 Edit Delete' }).getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('heading', { name: 'Listes des etablissements' }).click();
  await page.getByRole('columnheader', { name: 'code' }).click();
  await page.getByRole('columnheader', { name: 'Nom' }).click();
  await page.getByRole('columnheader', { name: 'Telephone' }).click();
  await page.getByRole('columnheader', { name: 'Fax' }).click();
  await page.getByRole('columnheader', { name: 'ville' }).click();
  await page.getByRole('columnheader', { name: 'Nbr_enseignants' }).click();
  await page.getByRole('link', { name: 'Gestion de grade' }).click();
  await page.getByRole('button', { name: 'Ajouter grade' }).click();
  await page.getByLabel('Designantion:').click();
  await page.getByLabel('Designantion:').fill('testgrade');
  await page.getByLabel('Charge_statutaire:').click();
  await page.getByLabel('Charge_statutaire:').fill('500');
  await page.getByLabel('Taux_horaire_Vocation:').click();
  await page.getByLabel('Taux_horaire_Vocation:').fill('1000');
  await page.getByRole('button', { name: 'Ajouter', exact: true }).click();
  await page.getByRole('row', { name: 'testgrade 500 1000 Edit Delete' }).getByRole('link', { name: 'Edit' }).click();
  await page.getByLabel('Taux Horraire Vocation :').click();
  await page.getByLabel('Taux Horraire Vocation :').fill('850');
  await page.getByRole('button', { name: 'Soumettre' }).click();
  await page.getByRole('row', { name: 'testgrade 500 850 Edit Delete' }).getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('heading', { name: 'Listes de grade' }).click();
  await page.getByRole('columnheader', { name: 'Designantion' }).click();
  await page.getByRole('columnheader', { name: 'Charge_statutaire' }).click();
  await page.getByRole('columnheader', { name: 'Taux_horaire_Vocation' }).click();
  await page.getByRole('link', { name: 'Gestion des directeurs' }).click();
  await page.getByRole('heading', { name: 'Listes des directeurs d\'établissement' }).click();
  await page.getByRole('columnheader', { name: 'email' }).click();
  await page.getByRole('columnheader', { name: 'PPR' }).click();
  await page.getByText('Nom', { exact: true }).click();
  await page.getByText('Prenom').click();
  await page.getByText('Etablissement', { exact: true }).click();
  await page.getByRole('button', { name: 'Ajouter' }).click();
  await page.getByLabel('PPR:').click();
  await page.getByLabel('PPR:').fill('21354');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('direct@etab.com');
  await page.getByLabel('Nom:', { exact: true }).click();
  await page.getByLabel('Nom:', { exact: true }).fill('test');
  await page.getByLabel('Nom:', { exact: true }).press('Tab');
  await page.getByLabel('Prénom:').fill('test');
  await page.getByRole('button', { name: 'Ajouter' }).nth(1).click();
  await page.getByRole('link', { name: 'Edit' }).click();
  await page.getByLabel('Nom:', { exact: true }).click();
  await page.getByLabel('Nom:', { exact: true }).fill('tester');
  await page.getByRole('button', { name: 'Soumettre' }).click();
  await page.getByRole('button', { name: 'Ajouter' }).click();
  await page.getByLabel('PPR:').click();
  await page.getByLabel('PPR:').fill('7777');
  await page.locator('div').filter({ hasText: /^email:$/ }).click();
  await page.locator('input[type="email"]').fill('testsupr@etab.com');
  await page.locator('input[type="email"]').press('Tab');
  await page.getByLabel('Nom:', { exact: true }).fill('test');
  await page.getByLabel('Nom:', { exact: true }).press('Tab');
  await page.getByLabel('Prénom:').fill('test');
  await page.getByRole('button', { name: 'Ajouter' }).nth(1).click();
  await page.getByRole('row', { name: 'testsupr@etab.com 7777 test test UAE Edit Delete' }).getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('link', { name: 'Gestion des profs' }).click();
  await page.getByRole('heading', { name: 'Listes des profs' }).click();
  await page.getByRole('cell', { name: 'PPR' }).click();
  await page.getByRole('cell', { name: 'NOM', exact: true }).click();
  await page.getByRole('cell', { name: 'PRENOM' }).click();
  await page.getByRole('cell', { name: 'DATE DE NAISSANCE' }).click();
  await page.getByRole('cell', { name: 'ETABLISSEMENT' }).click();
  await page.getByRole('cell', { name: 'GRADE' }).click();
  await page.getByRole('button', { name: 'Ajouter' }).click();
  await page.getByLabel('PPR:').click();
  await page.getByLabel('PPR:').fill('9754612');
  await page.getByLabel('Nom:', { exact: true }).click();
  await page.getByLabel('Nom:', { exact: true }).fill('test');
  await page.getByLabel('Prenom:').click();
  await page.getByLabel('Prenom:').fill('prof');
  await page.getByLabel('Email:').click();
  await page.getByLabel('Email:').fill('prof@etab.com');
  await page.getByLabel('DATE_NAISSANCE:').fill('2023-05-30');
  await page.getByRole('combobox', { name: 'Grade: Etablisssement Origine:' }).selectOption('2');
  await page.locator('div').filter({ hasText: /^Etablisssement Origine:Selectionner etablissement FPL$/ }).locator('#type').selectOption('2');
  await page.getByRole('button', { name: 'Ajouter' }).nth(1).click();
  await page.getByRole('button', { name: 'Ajouter' }).click();
  await page.getByLabel('PPR:').click();
  await page.getByLabel('PPR:').fill('41952');
  await page.getByLabel('Nom:', { exact: true }).click();
  await page.getByLabel('Nom:', { exact: true }).fill('test');
  await page.getByLabel('Nom:', { exact: true }).press('Tab');
  await page.getByLabel('Prenom:').fill('test');
  await page.getByLabel('Email:').click();
  await page.getByLabel('Email:').fill('profsupr@supr.com');
  await page.getByLabel('DATE_NAISSANCE:').fill('2023-06-08');
  await page.getByRole('combobox', { name: 'Grade: Etablisssement Origine:' }).selectOption('1');
  await page.locator('div').filter({ hasText: /^Etablisssement Origine:Selectionner etablissement FPL$/ }).locator('#type').selectOption('2');
  await page.getByRole('button', { name: 'Ajouter' }).nth(1).click();
  await page.getByRole('row', { name: '41952 test test 2023-06-08 FPL Prof Hab Editer Supprimer' }).getByRole('link', { name: 'Editer' }).click();
  await page.getByLabel('Prenom:').click();
  await page.getByLabel('Prenom:').fill('tes');
  await page.getByRole('button', { name: 'Soumettre' }).click();
  await page.getByRole('row', { name: '41952 test tes 2023-06-08 FPL Prof Hab Editer Supprimer' }).getByRole('button', { name: 'Supprimer' }).click();
  await page.locator('section div').filter({ hasText: 'PPRNOMPRENOM DATE DE NAISSANCE ETABLISSEMENT GRADE Ajouter 9754612testprof2023-0' }).nth(1).click();
  await page.getByRole('link', { name: 'Gestion des interventions' }).click();
  await page.getByLabel('PPR').click();
  await page.getByLabel('PPR').fill('97546');
  await page.getByLabel('Intitulé intervention').click();
  await page.getByLabel('Intitulé intervention').fill('test intervention');
  await page.getByLabel('Nombre Heure').click();
  await page.getByLabel('Nombre Heure').fill('42');
  await page.getByLabel('Année Scolaire').click();
  await page.getByLabel('Année Scolaire').fill('2022/2023');
  await page.locator('#underline_select').first().selectOption('Semestre 2');
  await page.locator('#underline_select').nth(1).selectOption('2');
  await page.locator('#underline_select').nth(1).selectOption('4');
  await page.getByLabel('Date Debut').fill('2023-06-09');
  await page.getByLabel('Date Fin').fill('2023-06-02');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.frameLocator('#webpack-dev-server-client-overlay').getByText('Uncaught runtime errors:×ERRORRequest failed with status code 422 AxiosError: Re').click({
    button: 'right'
  });
  await page.getByLabel('PPR').click();
  await page.getByLabel('PPR').fill('9754612');
  await page.getByLabel('Intitulé intervention').click();
  await page.getByLabel('Intitulé intervention').fill('test intervention1');
  await page.getByLabel('Nombre Heure').click();
  await page.getByLabel('Nombre Heure').fill('42');
  await page.getByLabel('Année Scolaire').click();
  await page.getByLabel('Année Scolaire').fill('2022/2023');
  await page.locator('#underline_select').first().selectOption('Semestre 2');
  await page.locator('#underline_select').nth(1).selectOption('4');
  await page.getByLabel('Date Debut').fill('2023-06-04');
  await page.getByLabel('Date Fin').fill('2023-06-30');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('InfoInfo alert! Intervention Crée avec Succes.').click();
  await page.getByText('Info alert! Intervention Crée avec Succes.').click();
  await page.getByRole('link', { name: 'Gestion de président' }).click();
  await page.getByRole('heading', { name: 'Gestion de président' }).click();
  await page.getByRole('columnheader', { name: 'email' }).click();
  await page.getByRole('columnheader', { name: 'PPR' }).click();
  await page.getByText('Nom', { exact: true }).click();
  await page.getByRole('columnheader', { name: 'Prenom' }).click();
  await page.getByRole('button', { name: 'Ajouter' }).click();
  await page.getByRole('button', { name: 'Ajouter' }).click();
  await page.getByLabel('Email:').click();
  await page.getByLabel('Email:').press('ArrowRight');
  await page.getByLabel('Email:').press('ArrowRight');
  await page.getByLabel('Email:').press('ArrowRight');
  await page.getByLabel('Email:').fill('admin@univ.com');
  await page.getByLabel('PPR:').click();
  await page.getByLabel('PPR:').fill('235689');
  await page.getByLabel('Nom:', { exact: true }).click();
  await page.getByLabel('Nom:', { exact: true }).fill('test');
  await page.getByLabel('Nom:', { exact: true }).press('Tab');
  await page.getByLabel('Prénom:').fill('test');
  await page.getByRole('button', { name: 'Ajouter' }).nth(1).click();
  await page.getByRole('row', { name: 'markundacratt0@gmail.com 1565431 lalali lolali Edit Delete' }).getByRole('link', { name: 'Edit' }).click();
  await page.getByLabel('Prénom:').click();
  await page.getByLabel('Prénom:').fill('lolal');
  await page.getByRole('button', { name: 'Soumettre' }).click();
  await page.getByText('Déconnexion').click();
});