import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8080/');
  await page.getByPlaceholder('Enter Email Address').fill('Soufianbouktaib1@gmail.com');
  await page.getByPlaceholder('Enter Password').click();
  await page.getByPlaceholder('Enter Password').fill('test');
  await page.getByPlaceholder('Enter Password').press('Enter');
  await page.getByText('Admin').click();
  await page.getByText('Soufianbouktaib1@gmail.com').click();
  await page.locator('img').click();
  await page.locator('#app div').filter({ hasText: 'Email:PPR:Établissement:Nom:Prénom: Modifier' }).nth(3).click();
  await page.locator('.h-\\[calc\\(100vh-50px\\)\\] > div').first().click();
  await page.getByRole('link', { name: 'Profil' }).click();
  await page.getByRole('button', { name: 'Modifier' }).click();
  await page.locator('.modal-content > div:nth-child(4) > .border').click();
  await page.locator('.modal-content > div:nth-child(4) > .border').fill('Soufian');
  await page.getByRole('button', { name: 'Modifer' }).click();
  await page.getByRole('link', { name: 'Consultation des etats de paiements' }).click();
  await page.locator('.border').click();
  await page.getByRole('heading', { name: 'Consulter les etats de paiments de année actuelle' }).click();
  await page.getByText('Nom', { exact: true }).click();
  await page.getByText('Prenom').click();
  await page.getByText('VH').click();
  await page.getByRole('columnheader', { name: 'Taux_H' }).click();
  await page.getByText('Brut').click();
  await page.getByText('IR', { exact: true }).click();
  await page.getByText('Net').click();
  await page.getByText('Annee_univ').click();
  await page.getByText('semestre', { exact: true }).click();
  await page.getByRole('link', { name: 'Consultation des Interventions' }).click();
  await page.getByRole('heading', { name: 'Consultation des interventions' }).click();
  await page.getByRole('columnheader', { name: 'Intitule_intervention' }).click();
  await page.getByRole('columnheader', { name: 'Nom', exact: true }).click();
  await page.getByText('Prenom').click();
  await page.getByText('Annee_univ').click();
  await page.getByText('Semestre', { exact: true }).click();
  await page.getByText('Date_debut').click();
  await page.getByText('Date_fin').click();
  await page.getByRole('columnheader', { name: 'Nbr_heures' }).click();
  await page.getByRole('columnheader', { name: 'Visa_uae' }).click();
  await page.getByRole('columnheader', { name: 'Visa_etb' }).click();
  await page.getByRole('link', { name: 'Gestion des Interventions' }).click();
  await page.getByRole('heading', { name: 'Gestion des Interventions' }).click();
  await page.getByRole('columnheader', { name: 'Intitule_intervention' }).click();
  await page.getByText('Annee_univ').click();
  await page.getByText('Semestre', { exact: true }).click();
  await page.getByRole('columnheader', { name: 'Nbr_heures' }).click();
  await page.getByText('Date_debut').click();
  await page.getByText('Date_fin').click();
  await page.getByRole('columnheader', { name: 'Etat' }).click();
  await page.getByRole('columnheader', { name: 'Operation' }).click();
  await page.getByRole('button', { name: 'valider', exact: true }).click();
  await page.getByRole('row', { name: 'Séminaire sur la gestion des ressources humaines 2022/2023 Semestre 2 15 2023-03-05 2023-03-07 valide invalider' }).getByRole('button', { name: 'invalider' }).click();
  await page.getByRole('heading', { name: 'Directeur d\'etablissement' }).click();
  await page.getByText('Déconnexion').click();
});