import { test, expect } from '@playwright/test';

test('PresidentInterface', async ({ page }) => {
  await page.goto('http://localhost:8080/');
  await page.getByPlaceholder('Enter Email Address').fill('okabe2015rintaro@gmail.com');
  await page.getByPlaceholder('Enter Password').click();
  await page.getByPlaceholder('Enter Password').fill('test');
  await page.getByPlaceholder('Enter Password').press('Enter');
  await page.getByRole('listitem').click();
  await page.getByRole('listitem').getByText('Président').click();
  await page.getByText('okabe2015rintaro@gmail.com').click();
  await page.getByRole('img', { name: 'Neil image' }).click();
  await page.getByText('Email:PPR:Nom:Prénom: Modifier').click();
  await page.getByRole('button', { name: 'Modifier' }).click();
  await page.locator('.mb-4 > .border').first().click();
  await page.locator('.mb-4 > .border').first().fill('Achernan');
  await page.getByRole('button', { name: 'Modifer' }).click();
  await page.getByRole('button', { name: 'Modifier' }).click();
  await page.locator('.mb-4 > .border').first().click();
  await page.locator('.mb-4 > .border').first().fill('Achernane');
  await page.getByRole('button', { name: 'Modifer' }).click();
  await page.locator('.h-\\[calc\\(100vh-50px\\)\\] > div').first().click();
  await page.getByRole('link', { name: 'Profil' }).click();
  await page.getByRole('link', { name: 'Consultation des paiements' }).click();
  await page.locator('.border').click();
  await page.getByRole('heading', { name: 'Consulter les etats de paiments d\'année actuelle' }).click();
  await page.getByRole('columnheader', { name: 'Nom', exact: true }).click();
  await page.getByText('Prenom').click();
  await page.getByText('Etablissement').click();
  await page.getByText('VH').click();
  await page.getByText('Taux_H').click();
  await page.getByText('Brut').click();
  await page.getByText('IR').click();
  await page.getByText('Net').click();
  await page.getByText('Annee_univ').click();
  await page.getByText('semestre', { exact: true }).click();
  await page.getByRole('cell', { name: 'Mansouri' }).click();
  await page.getByRole('cell', { name: 'Amina' }).click();
  await page.getByRole('cell', { name: 'École Nationale de Commerce et de Gestion de Tanger' });
  await page.getByRole('cell', { name: '35' }).click();
  await page.getByRole('row', { name: 'Mansouri Amina École Nationale de Commerce et de Gestion de Tanger 35 300 10500 0.38 6510 2022/2023 Semestre 1' }).getByRole('cell', { name: '300' }).click();
  await page.getByRole('cell', { name: '10500' }).click();
  await page.getByRole('row', { name: 'Mansouri Amina École Nationale de Commerce et de Gestion de Tanger 35 300 10500 0.38 6510 2022/2023 Semestre 1' }).getByRole('cell', { name: '0.38' }).click();
  await page.getByRole('cell', { name: '6510' }).click();
  await page.getByRole('row', { name: 'Mansouri Amina École Nationale de Commerce et de Gestion de Tanger 35 300 10500 0.38 6510 2022/2023 Semestre 1' }).getByRole('cell', { name: '2022/2023' }).click();
  await page.getByRole('row', { name: 'Mansouri Amina École Nationale de Commerce et de Gestion de Tanger 35 300 10500 0.38 6510 2022/2023 Semestre 1' }).getByRole('cell', { name: 'Semestre 1' }).click();
  await page.getByRole('link', { name: 'Gestion des Interventions' }).click();
  await page.getByRole('heading', { name: 'Gestion des Interventions' }).click();
  await page.getByText('Gestion des InterventionsIntitule_interventionNomPrenom Etablissement Annee_univ').click();
  await page.getByRole('cell', { name: 'Intitule_intervention' }).click();
  await page.getByRole('cell', { name: 'Nom', exact: true }).click();
  await page.getByRole('cell', { name: 'Prenom' }).click();
  await page.getByRole('cell', { name: 'Etablissement' }).click();
  await page.getByRole('cell', { name: 'Annee_univ' }).click();
  await page.getByRole('cell', { name: 'Semestre', exact: true }).click();
  await page.getByRole('cell', { name: 'Nbr_heures' }).click();
  await page.getByRole('cell', { name: 'Date_debut' }).click();
  await page.getByRole('cell', { name: 'Date_fin' }).click();
  await page.getByRole('cell', { name: 'Etat' }).click();
  await page.getByRole('cell', { name: 'Operation' }).click();
  await page.getByRole('cell', { name: 'invalide', exact: true });
  await page.getByRole('cell', { name: '2022-09-30' });
  await page.getByRole('cell', { name: '2022-09-01' });
  await page.getByRole('cell', { name: '20', exact: true });
  await page.getByRole('cell', { name: 'Semestre 1' });
  await page.getByRole('cell', { name: 'École Nationale de Commerce et de Gestion de Tanger' });
  await page.getByRole('cell', { name: 'Amina' });
  await page.getByRole('cell', { name: 'Mansouri' });
  await page.getByRole('cell', { name: 'Atelier de recherche' });
  await page.getByRole('cell', { name: 'Conférence sur le Metaverse' });
 await page.getByRole('row', { name: 'Conférence sur le Metaverse Amine Taha Faculté des Lettres et des Sciences Humaines 2022/2023 Semestre2 34 2023-01-29 2023-05-27 valide invalider' }).getByRole('cell', { name: '2022/2023' });
  await page.getByRole('cell', { name: 'Semestre2' });
  await page.getByRole('cell', { name: '2023-01-29' });
  await page.getByRole('cell', { name: '2023-05-27' });
  await page.getByRole('row', { name: 'Conférence sur le Metaverse Amine Taha Faculté des Lettres et des Sciences Humaines 2022/2023 Semestre2 34 2023-01-29 2023-05-27 valide invalider' }).getByRole('cell', { name: 'valide', exact: true });
  await page.getByRole('link', { name: 'Consultations des Interventions' }).click();
  await page.getByText('Listes des directeurs d\'établissement Filtrer par Etablissement Tous les etablis').click();
  await page.getByRole('heading', { name: 'Listes des directeurs d\'établissement' }).click();
  await page.getByText('Filtrer par Etablissement').click();
  await page.getByRole('combobox', { name: 'Filtrer par Etablissement' }).selectOption('Faculté des Sciences et Technique');
  await page.getByRole('combobox', { name: 'Filtrer par Etablissement' }).selectOption('Faculté des Lettres et des Sciences Humaines');
  await page.getByRole('combobox', { name: 'Filtrer par Etablissement' }).selectOption('École Nationale de Commerce et de Gestion de Tanger');
  await page.getByRole('combobox', { name: 'Filtrer par Etablissement' }).selectOption('École nationale des sciences appliquées de Tanger');
  await page.getByRole('combobox', { name: 'Filtrer par Etablissement' }).selectOption('Faculté de Medecine Tanger');
  await page.getByRole('cell', { name: 'Intitule_intervention' }).click();
  await page.getByRole('cell', { name: 'Nom', exact: true });
  await page.getByRole('cell', { name: 'Prenom' }).click();
  await page.getByRole('cell', { name: 'Etablissement' }).click();
  await page.getByRole('cell', { name: 'Annee_univ' }).click();
  await page.getByRole('cell', { name: 'Semestre' });
  await page.getByRole('cell', { name: 'Date_debut' }).click();
  await page.getByRole('cell', { name: 'Date_fin' }).click();
  await page.getByRole('cell', { name: 'Nbr_heures' }).click();
  await page.getByRole('cell', { name: 'Visa_uae' }).click();
  await page.getByRole('cell', { name: 'Visa_etb' }).click();
  await page.getByText('Déconnexion').click();
});